spring.application.name=reactifs-management

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/reactifs_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:ouz4real}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET:uasz-reactifs-secret-key-must-be-at-least-32-chars-long}
jwt.expiration=86400000
